### ISSUE TITLE
Retry logic not working as expected

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-s3#2]
The improved retry logic is still not working as expected. It was anticipated that the below should not occur after fix in 2d7890c

```
Traceback (most recent call last):
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/s3transfer/tasks.py", line 364, in _main
    **extra_args)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchUpload: An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/users/JIC_a5/olssont/envs/dm/bin/dtool", line 11, in <module>
    load_entry_point('dtool-cli==0.7.0', 'console_scripts', 'dtool')()
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/dtool_create/dataset.py", line 521, in cp
    _copy(resume, quiet, dataset_uri, dest_base_uri)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/dtool_create/dataset.py", line 488, in _copy
    progressbar=progressbar
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/dtoolcore/__init__.py", line 224, in copy_resume
    _copy_content(dataset, proto_dataset, progressbar)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/dtoolcore/__init__.py", line 165, in _copy_content
    dest_proto_dataset.put_item(src_abspath, relpath)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/dtoolcore/__init__.py", line 544, in put_item
    return self._storage_broker.put_item(fpath, relpath)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/dtool_s3/storagebroker.py", line 381, in put_item
    'checksum': checksum,
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/users/JIC_a5/olssont/envs/dm/lib64/python3.6/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload /usr/users/a5/olssont/group_data/informatics_scratch/watseq_matrix/watseq.snp.indel.matrix/data/vcf_split/merged_chr5B_part1.vcf.gz to pr-raw-watseq/7036c101-01aa-4180-92e7-25de1c0cc6dc/data/0df2a3206023845d309f280557a81cbd78e9d507: An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.
```

**Comment by tjelvar-olsson** [comment]
This might be a red herring because the wrong version of dtool-s3 was installed.

Installed:
s3, dtool-s3, version 0.6.0

Expected:
dtool-s3-0.9.0

**Comment by tjelvar-olsson** [comment]
Red herring. Closing
