### ISSUE TITLE
AttributeError: 'S3StorageBroker' object has no attribute 'dataset_prefix'

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-s3#6]
@pastewka I believe this issue was introduced by merging: https://github.com/jic-dtool/dtool-s3/pull/3

```
$ dtool ls s3://test-dtool-s3-bucket-to
Traceback (most recent call last):
  File "c:\users\tjelv\projects\dtool\dtool-s3\dtool_s3\storagebroker.py", line 247, in _get_prefix
    rkey = self.s3resource.Object(
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\boto3-1.17.94-py3.9.egg\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\boto3-1.17.94-py3.9.egg\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\botocore-1.20.94-py3.9.egg\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\botocore-1.20.94-py3.9.egg\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tools\Anaconda3\envs\dtool-dev\Scripts\dtool-script.py", line 33, in <module>
    sys.exit(load_entry_point('dtool-cli', 'console_scripts', 'dtool')())
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\tools\Anaconda3\envs\dtool-dev\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\tjelv\projects\dtool\dtool-info\dtool_info\dataset.py", line 182, in ls
    if dtoolcore._is_dataset(uri, CONFIG_PATH):
  File "c:\users\tjelv\projects\dtool\dtoolcore\dtoolcore\__init__.py", line 84, in _is_dataset
    storage_broker = _get_storage_broker(uri, config_path)
  File "c:\users\tjelv\projects\dtool\dtoolcore\dtoolcore\__init__.py", line 63, in _get_storage_broker
    storage_broker = StorageBroker(uri, config_path)
  File "c:\users\tjelv\projects\dtool\dtool-s3\dtool_s3\storagebroker.py", line 217, in __init__
    self.data_key_prefix = self._generate_key_prefix("data_key_infix")
  File "c:\users\tjelv\projects\dtool\dtool-s3\dtool_s3\storagebroker.py", line 268, in _generate_key_prefix
    return self._generate_key(structure_dict_key) + '/'
  File "c:\users\tjelv\projects\dtool\dtool-s3\dtool_s3\storagebroker.py", line 264, in _generate_key
    prefix = self._get_prefix(structure_dict_key)
  File "c:\users\tjelv\projects\dtool\dtool-s3\dtool_s3\storagebroker.py", line 257, in _get_prefix
    self._prefix = '' if self.dataset_prefix is None \
AttributeError: 'S3StorageBroker' object has no attribute 'dataset_prefix'
```

**Comment by tjelvar-olsson** [comment]
Fixed in 0d1f39d

**Comment by pastewka** [comment]
Thanks for fixing this. I'm surprised this did not show up earlier - did this turn up when using the s3 not the ecs storage broker?

**Comment by tjelvar-olsson** [comment]
S3, I don't have a means to test on ECS at the moment
